// note that all " marks have been escaped
// so that this can be included as a string
"function showTime() {\n"
"    var date = new Date();\n"
"    var h = date.getHours(); // 0 - 23\n"
"    var m = date.getMinutes(); // 0 - 59\n"
"    var s = date.getSeconds(); // 0 - 59\n"
"    var session = \"AM\";\n"
"    \n"
"    if(h == 0){\n"
"        h = 12;\n"
"    }\n"
"    \n"
"    if(h > 12){\n"
"        h = h - 12;\n"
"        session = \"PM\";\n"
"    }\n"
"    \n"
"    h = (h < 10) ? \"0\" + h : h;\n"
"    m = (m < 10) ? \"0\" + m : m;\n"
"    s = (s < 10) ? \"0\" + s : s;\n"
"    \n"
"    var time = h + \":\" + m + \" \" + session;\n"
"    document.getElementById(\"MyClockDisplay\").innerText = time;\n"
"    document.getElementById(\"MyClockDisplay\").textContent = time;\n"
"    \n"
"    setTimeout(showTime, 1000);\n"
"}"
